default_pruebas:
   path: /test
   controller: App\Controller\DefaultController::tests
default_signup:
   path: /test
   controller: App\Controller\DefaultController::signup
default_login:
   path: /login
   controller: App\Controller\DefaultController::login
   methods:   [POST]